"""Generate the GRACE Hello MCP icon(s) with zero dependencies (stdlib only).

Renders a badge: a vertical gradient background with a clean white ring mark in
the center, anti-aliased so it looks intentional. The design is full-bleed and
fully opaque on purpose: some clients composite favicons onto a white tile, so a
transparent or non-square icon would look wrong.

Outputs (into public/, which both Render and Vercel serve as the web root):
  - public/icon.png      (512x512)  -> served over HTTPS, advertised to clients
  - public/icon-128.png  (128x128)  -> the source for the data: URI fallback
  - public/favicon.ico   (128x128 PNG bytes) -> site favicon (for Google's
                                        favicon service -> Claude connector icon)
And, for runtime use without filesystem reads (important on serverless):
  - icon-data.js  -> exports ICON_DATA_URI (base64 of the 128px icon)
"""
import base64
import os
import shutil
import struct
import zlib

TOP = (15, 32, 39)      # #0F2027
BOTTOM = (44, 83, 100)  # #2C5364
RING = (43, 212, 196)   # #2BD4C4 teal
WHITE = (240, 248, 247)


def lerp(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


def smoothstep(edge0, edge1, x):
    if edge0 == edge1:
        return 0.0 if x < edge0 else 1.0
    t = max(0.0, min(1.0, (x - edge0) / (edge1 - edge0)))
    return t * t * (3 - 2 * t)


def chunk(typ, data):
    return (
        struct.pack(">I", len(data))
        + typ
        + data
        + struct.pack(">I", zlib.crc32(typ + data) & 0xFFFFFFFF)
    )


def render(size):
    """Return PNG bytes for a square icon of the given pixel size."""
    cx = cy = size / 2.0
    ring_radius = size * 0.30
    ring_half_thickness = size * 0.075
    dot_radius = size * 0.085
    aa = size / 512.0 * 1.5  # anti-alias softness scaled to size

    raw = bytearray()
    for y in range(size):
        raw.append(0)  # PNG filter type 0 for this scanline
        bg = lerp(TOP, BOTTOM, y / (size - 1))
        for x in range(size):
            dist = ((x - cx) ** 2 + (y - cy) ** 2) ** 0.5
            r, g, b = bg

            ring_d = abs(dist - ring_radius)
            ring_a = 1.0 - smoothstep(ring_half_thickness - aa,
                                      ring_half_thickness + aa, ring_d)
            if ring_a > 0:
                r, g, b = lerp((r, g, b), RING, ring_a)

            dot_a = 1.0 - smoothstep(dot_radius - aa, dot_radius + aa, dist)
            if dot_a > 0:
                r, g, b = lerp((r, g, b), WHITE, dot_a)

            raw += bytes((r, g, b))

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)  # 8-bit RGB
    idat = zlib.compress(bytes(raw), 9)
    return sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b"")


os.makedirs("public", exist_ok=True)

png512 = render(512)
png128 = render(128)

with open("public/icon.png", "wb") as f:
    f.write(png512)
    print(f"Wrote public/icon.png ({len(png512)} bytes, 512x512)")

with open("public/icon-128.png", "wb") as f:
    f.write(png128)
    print(f"Wrote public/icon-128.png ({len(png128)} bytes, 128x128)")

# favicon.ico: most browsers and Google's favicon crawler accept PNG bytes here.
with open("public/favicon.ico", "wb") as f:
    f.write(png128)
    print(f"Wrote public/favicon.ico ({len(png128)} bytes, PNG/128x128)")

# Embed the small icon as a base64 data: URI in a JS module so serverless
# functions don't need to read the filesystem at runtime.
b64 = base64.b64encode(png128).decode("ascii")
with open("icon-data.js", "w") as f:
    f.write("// AUTO-GENERATED by make_icon.py — do not edit by hand.\n")
    f.write(f'export const ICON_DATA_URI = "data:image/png;base64,{b64}";\n')
    print(f"Wrote icon-data.js (data: URI, {len(b64)} base64 chars)")
